using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace GitBash
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("Hello world!");
            Console.ReadKey();
            Console.Clear();
            {
                Console.Write("W");
                Thread.Sleep(250);
                Console.Write("a");
                Thread.Sleep(250);
                Console.Write("k");
                Thread.Sleep(250);
                Console.Write("e");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("u");
                Thread.Sleep(250);
                Console.Write("p");
                Thread.Sleep(250);
                Console.Write(",");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("N");
                Thread.Sleep(250);
                Console.Write("e");
                Thread.Sleep(250);
                Console.Write("o");
                Thread.Sleep(250);
                Console.Write(".");
                Thread.Sleep(250);
                Console.Write(".");
                Thread.Sleep(250);
                Console.Write(".");
                Thread.Sleep(2000);
                Console.Clear();
                Console.Write("T");
                Thread.Sleep(250);
                Console.Write("h");
                Thread.Sleep(250);
                Console.Write("e");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("M");
                Thread.Sleep(250);
                Console.Write("a");
                Thread.Sleep(250);
                Console.Write("t");
                Thread.Sleep(250);
                Console.Write("r");
                Thread.Sleep(250);
                Console.Write("i");
                Thread.Sleep(250);
                Console.Write("x");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("h");
                Thread.Sleep(250);
                Console.Write("a");
                Thread.Sleep(250);
                Console.Write("s");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("y");
                Thread.Sleep(250);
                Console.Write("o");
                Thread.Sleep(250);
                Console.Write("u");
                Thread.Sleep(250);
                Console.Write(".");
                Thread.Sleep(250);
                Console.Write(".");
                Thread.Sleep(250);
                Console.Write(".");
                Thread.Sleep(2000);
                Console.Clear();
                Console.Write("F");
                Thread.Sleep(250);
                Console.Write("o");
                Thread.Sleep(250);
                Console.Write("l");
                Thread.Sleep(250);
                Console.Write("l");
                Thread.Sleep(250);
                Console.Write("o");
                Thread.Sleep(250);
                Console.Write("w");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("t");
                Thread.Sleep(250);
                Console.Write("h");
                Thread.Sleep(250);
                Console.Write("e");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("w");
                Thread.Sleep(250);
                Console.Write("h");
                Thread.Sleep(250);
                Console.Write("i");
                Thread.Sleep(250);
                Console.Write("t");
                Thread.Sleep(250);
                Console.Write("e");
                Thread.Sleep(250);
                Console.Write(" ");
                Thread.Sleep(250);
                Console.Write("r");
                Thread.Sleep(500);
                Console.Write("a");
                Thread.Sleep(250);
                Console.Write("b");
                Thread.Sleep(250);
                Console.Write("b");
                Thread.Sleep(250);
                Console.Write("i");
                Thread.Sleep(250);
                Console.Write("t");
                Thread.Sleep(250);
                Console.Write(".");
                Console.ReadKey();
            }
        }
    }
}
